
system: "base16"
name: "IC-Orange-PPL-trim"
author: "FredHappyface (https://github.com/fredHappyface)"
variant: "dark"
palette:
  base00: "#000000"
  base01: "#c13900"
  base02: "#a4a900"
  base03: "#caaf00"
  base04: "#bd6d00"
  base05: "#fc5e00"
  base06: "#f79500"
  base07: "#ffc88a"
  base08: "#6a4f2a"
  base09: "#ff8c68"
  base0A: "#f6ff40"
  base0B: "#ffe36e"
  base0C: "#ffbe55"
  base0D: "#fc874f"
  base0E: "#c69752"
  base0F: "#fafaff"
